version: '3'

services:
  nestjs:
    build: ./backend
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - ./backend:/home/node/app
  
  nextjs:
    build: ./frontend
    ports:
      - 3001:3000
    volumes:
      - ./frontend:/home/node/app
  db:
    image: bitnami/mongodb:5.0.17
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/bitnami/mongodb
    environment:
      MONGODB_ROOT_PASSWORD: root
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: 123456
      MONGODB_DATABASE: nest

volumes:
  mongodb_data:
    driver: local