GET http://localhost:3000/routes

###
POST http://localhost:3000/routes
Content-Type: application/json

{
    "name": "Varginha - State of Minas Gerais, Brazil - Lavras, State of Minas Gerais, 37200-000, Brazil",
    "source_id": "ChIJCQyKfpKSypQR4CAwqYF4WmA",
    "destination_id": "ChIJ-QOxOYD9nwAR87Fco_v84zk"
}

###
GET http://localhost:3000/places?text=betim, mg

###
GET http://localhost:3000/places?text=belo horizonte, mg

###
GET http://localhost:3000/directions?originId=ChIJmx-wX0rCpgARjxH_rJ8d5do&destinationId=ChIJMyzPysqQpgARlznSOl55NVs